-- ============================================================
-- Greyhaven Real Estate — run this ONCE in your Supabase
-- project's SQL Editor to enable shared mode.
--
-- It only ADDS two tables; nothing else in the project is
-- touched, so it's safe to run in a project that other apps
-- already use.
--
-- Trust model: anyone holding the project's anon public key
-- (i.e. anyone you give a copy of the app to) can read AND
-- write these two tables. Other tables in the project are
-- unaffected as long as they don't grant anon policies of
-- their own. Keep occasional EXPORT backups in case someone
-- griefs the map — IMPORT restores it.
-- ============================================================

create table if not exists public.re_properties (
  id          bigint primary key,          -- generated by the app
  name        text not null,
  type        text,
  status      text,
  price       bigint default 0,
  owner       text,
  garage      text,
  description text,
  photo       text,                        -- compressed data-URL screenshot
  x           double precision,
  y           double precision,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

create table if not exists public.re_zones (
  id          bigint primary key,
  name        text not null,
  note        text,
  color       text,
  coordinates jsonb                        -- [[y,x], ...] polygon vertices
);

alter table public.re_properties enable row level security;
alter table public.re_zones enable row level security;

drop policy if exists "re_properties_all" on public.re_properties;
drop policy if exists "re_zones_all" on public.re_zones;

create policy "re_properties_all" on public.re_properties
  for all to anon using (true) with check (true);

create policy "re_zones_all" on public.re_zones
  for all to anon using (true) with check (true);
